<?php

/**
 * @file
 * Let users import content from CSV or TSV file.
 */

/**
 * Implementation of hook_perm().
 */
function ps_import_perm() {
  return array('import content', 'administer imports');
}

/**
 * Implementation of hook_menu().
 */
function ps_import_menu() {
  $items = array();

  $items['admin/ps_import'] = array(
    'title' => 'Ps Import Data',
    'description' => 'Import content from a <abbr title="Comma Separated Values">CSV</abbr> or <abbr title="Tab Separated Values">TSV</abbr> file.',
    'access callback' => 'user_access',
    'access arguments' => array('import content'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ps_import_list_tasks_form'),
    'file' => 'ps_import.admin.inc',
  );

  $items['admin/ps_import/list'] = array(
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
    'title' => 'List',
  );

  $items['admin/ps_import/list/tasks'] = array(
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
    'title' => 'Tasks',
  );

  $items['admin/ps_import/list/files'] = array(
    'type' => MENU_LOCAL_TASK,
    'title' => 'Files',
    'access callback' => 'user_access',
    'access arguments' => array('import content'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ps_import_list_files_form'),
    'file' => 'ps_import.admin.inc',
  );

  $items['admin/ps_import/add'] = array(
    'type' => MENU_LOCAL_TASK,
    'title' => 'New import',
    'access callback' => 'user_access',
    'access arguments' => array('import content'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ps_import_add_form'),
    'file' => 'ps_import.admin.inc',
  );

  $items['admin/ps_import/settings'] = array(
    'type' => MENU_LOCAL_TASK,
    'title' => 'Settings',
    'weight' => 10,
    'access callback' => 'user_access',
    'access arguments' => array('administer imports'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ps_import_settings_form'),
    'file' => 'ps_import.admin.inc',
  );

  $items['admin/ps_import/%ps_import'] = array(
    'type' => MENU_CALLBACK,
    'title' => 'Importing...',
    'access callback' => 'ps_import_access',
    'access arguments' => array(2),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ps_import_view_form', 2),
    'file' => 'ps_import.admin.inc',
  );

  $items['admin/ps_import/%ps_import/view'] = array(
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'title' => 'View',
    'weight' => -10,
  );

  $items['admin/ps_import/%ps_import/continue'] = array(
    'type' => MENU_CALLBACK,
    'title' => 'Continue import',
    'access callback' => 'ps_import_access',
    'access arguments' => array(2),
    'page callback' => 'ps_import_js',
    'page arguments' => array(2),
    'file' => 'ps_import.inc',
  );

  $items['admin/ps_import/%ps_import/debug'] = array(
    'type' => MENU_CALLBACK,
    'title' => 'Debug report',
    'access callback' => 'ps_import_access',
    'access arguments' => array(2),
    'page callback' => 'ps_import_debug_report',
    'page arguments' => array(2),
    'file' => 'ps_import.admin.inc',
  );

  $items['admin/ps_import/%ps_import/delete'] = array(
    'type' => MENU_LOCAL_TASK,
    'title' => 'Delete',
    'weight' => 10,
    'access callback' => 'ps_import_access',
    'access arguments' => array(2),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ps_import_delete_form', 2),
    'file' => 'ps_import.admin.inc',
  );

  //TODO: %ps_import/clone ? %ps_import/edit ?

  return $items;
}

/**
 * Load an import task by id. Used in hook_menu().
 *
 * @param $taskid
 *   Integer.
 *
 * @return
 *   FALSE or the task object.
 *
 * @ingroup ps_import_tasks
 */
function ps_import_load($taskid) {
  if (isset($taskid)) {
    $values = db_fetch_array(db_query("SELECT * FROM {ps_import_tasks} WHERE taskid = %d", $taskid));
    if ($values !== FALSE) {
      foreach (array('file_options', 'headers', 'map', 'defaults', 'options') as $key) {
        $values[$key] = unserialize($values[$key]);
      }

      $values['file'] = db_fetch_object(db_query("SELECT * FROM {files} WHERE fid = %d", $values['fid']));

      module_invoke_all('ps_import_task', $values, 'load');
      return $values;
    }
  }

  return FALSE;
}

/**
 * Check access to an import task. Used in hook_menu().
 *
 * @param $task
 *   Array.
 *
 * @return
 *   TRUE if the current user can access the task.
 *
 * @ingroup ps_import_tasks
 */
function ps_import_access($task) {
  global $user;
  if (user_access('administer imports') || $task['uid'] == $user->uid) {
    return TRUE;
  }

  return FALSE;
}

/**
 * Implementation of hook_cron().
 */
function ps_import_cron() {
  module_load_include('inc', 'ps_import');

  $unit = variable_get('ps_import:cron:unit', 'rows');
  $count = variable_get('ps_import:cron:count', 25);

  ps_import_do_all_tasks($unit, $count);
}

/**
 * Implementation of hook_theme().
 */
function ps_import_theme() {
  return array(
    'ps_import_file_select' => array(
      'arguments' => array(
        'form' => NULL,
      ),
      'file' => 'ps_import.admin.inc',
    ),
    'ps_import_imports_list' => array(
      'arguments' => array(
        'form' => NULL,
      ),
      'file' => 'ps_import.admin.inc',
    ),
    'ps_import_file_format_select' => array(
      'arguments' => array(
        'form' => NULL,
      ),
      'file' => 'ps_import.admin.inc',
    ),
    'ps_import_sample_data' => array(
      'arguments' => array(
        'data' => NULL,
      ),
      'file' => 'ps_import.admin.inc',
    ),
    'ps_import_field_table' => array(
      'arguments' => array(
        'form' => NULL,
      ),
      'file' => 'ps_import.admin.inc',
    ),
  );
}

/**
 * Implementation of hook_nodeapi().
 */
function ps_import_nodeapi(&$node, $op) {
	if ($op == 'insert') {
        if($node->type == 'copier' || $node->type == 'printer' || $node->type == 'cartridge'){
			foreach($node->taxonomy as $key => $value){
				if($value->vid == 2 || $value->vid == 5 || $value->vid == 7){
					$model = $key;
					$brand = db_result(db_query('SELECT parent FROM {term_hierarchy} WHERE tid = %d',$key));
					db_query("INSERT INTO {node_brand} (nid, brand, model) VALUES (%d, %d, %d)",
$node->nid, $brand, $model);
				}
				if($value->vid == 3 || $value->vid == 4 || $value->vid == 6){
					$subcategory = $key;
					$category = db_result(db_query('SELECT parent FROM {term_hierarchy} WHERE tid = %d',$key));
					db_query("INSERT INTO {node_category} (nid, category, subcategory) VALUES (%d, %d, %d)",
$node->nid, $category, $subcategory);
				}
			}
		}
    }
}